export const LANGUAGES: Record<string, string> = {
  "Acehnese (Arabic script)": "ace_Arab",
  "Acehnese (Latin script)": "ace_Latn",
  "Afrikaans": "afr_Latn",
  "Albanian": "aln_Latn",
  "Amharic": "amh_Ethi",
  "Arabic": "ara_Arab",
  "Armenian": "hye_Armn",
  "Assamese": "asm_Beng",
  "Azerbaijani": "azj_Latn",
  "Belarusian": "bel_Cyrl",
  "Bengali": "ben_Beng",
  "Bosnian": "bos_Latn",
  "Bulgarian": "bul_Cyrl",
  "Burmese": "mya_Mymr",
  "Catalan": "cat_Latn",
  "Chinese (Simplified)": "zho_Hans",
  "Chinese (Traditional)": "zho_Hant",
  "Croatian": "hrv_Latn",
  "Czech": "ces_Latn",
  "Danish": "dan_Latn",
  "Dutch": "nld_Latn",
  "English": "eng_Latn",
  "Estonian": "est_Latn",
  "Finnish": "fin_Latn",
  "French": "fra_Latn",
  "German": "deu_Latn",
  "Greek": "ell_Grek",
  "Hebrew": "heb_Hebr",
  "Hindi": "hin_Deva",
  "Hungarian": "hun_Latn",
  "Icelandic": "isl_Latn",
  "Indonesian": "ind_Latn",
  "Italian": "ita_Latn",
  "Japanese": "jpn_Jpan",
  "Korean": "kor_Hang",
  "Latvian": "lav_Latn",
  "Lithuanian": "lit_Latn",
  "Macedonian": "mkd_Cyrl",
  "Malay": "msa_Latn",
  "Norwegian": "nob_Latn",
  "Persian": "fas_Arab",
  "Polish": "pol_Latn",
  "Portuguese": "por_Latn",
  "Romanian": "ron_Latn",
  "Russian": "rus_Cyrl",
  "Serbian": "srp_Cyrl",
  "Slovak": "slk_Latn",
  "Slovenian": "slv_Latn",
  "Spanish": "spa_Latn",
  "Swahili": "swh_Latn",
  "Swedish": "swe_Latn",
  "Tamil": "tam_Taml",
  "Thai": "tha_Thai",
  "Turkish": "tur_Latn",
  "Ukrainian": "ukr_Cyrl",
  "Urdu": "urd_Arab",
  "Vietnamese": "vie_Latn",
  "Welsh": "cym_Latn"
}; 